# Generated by Django 5.0 on 2024-02-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_blood_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_details',
            name='blood_type',
            field=models.CharField(max_length=128),
        ),
    ]
