# Generated by Django 5.0 on 2024-02-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_blood_details_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_details',
            name='days',
            field=models.IntegerField(default=None),
        ),
    ]
