# Generated by Django 5.0 on 2024-02-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_hospital_details_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital_details',
            name='org_phone',
        ),
        migrations.AddField(
            model_name='hospital_details',
            name='org_state',
            field=models.CharField(default=None, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_details',
            name='org_name',
            field=models.CharField(default=None, max_length=280, null=True),
        ),
    ]
